# build container
FROM node:alpine

RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.shrc" SHELL="$(which sh)" sh -

WORKDIR /usr/src/maw-photos
COPY "package.json" .
COPY "pnpm-lock.yaml" .

RUN /root/.local/share/pnpm/pnpm install

COPY . .

RUN /root/.local/share/pnpm/pnpm run build_test


# runtime container
FROM nginx:alpine

WORKDIR /srv/www/maw-photos

RUN rm /etc/nginx/conf.d/*

COPY etc/nginx/tls.conf                    /etc/nginx
COPY etc/nginx/test.nginx.conf             /etc/nginx/nginx.conf
COPY etc/nginx/h5bp                        /etc/nginx/h5bp
COPY etc/nginx/conf.d/test.maw-photos.conf /etc/nginx/conf.d/maw-photos.conf
COPY --from=0                              /usr/src/maw-photos/dist .

CMD [ "nginx", "-g", "daemon off;" ]
EXPOSE 4200
